// HOME PAGE
export const HOME_STATE_KEYS = {
  MENU_SELECTED_CAR_CATEGORY: "MENU_SELECTED_CAR_CATEGORY",
  MENU_SELECTED_CAR: "MENU_SELECTED_CAR",
  MENU_MAIN_IS_OPENED: "MENU_MAIN_IS_OPENED",
};

// MODEL SELECT PAGE
export const MODEL_SELECT_KEYS = {
  MODEL_SELECT_IS_CLOSE_MODAL_OPEN: "MODEL_SELECT_IS_CLOSE_MODAL_OPEN",
  MODEL_SEELCT_IS_SELECT_CAR_MODAL_OPEN:
    "MODEL_SEELCT_IS_SELECT_CAR_MODAL_OPEN",
  MODEL_SELECT_SELECTED_CATEGORY: "MODEL_SELECT_SELECTED_CATEGORY",
};
