// HOME PAGE
export const MENU_SELECTED_CAR_CATEGORY = "MENU_SELECTED_CAR_CATEGORY";
export const MENU_SELECTED_CAR = "MENU_SELECTED_CAR";
export const MENU_MAIN_IS_OPENED = "MENU_MAIN_IS_OPENED";

// MODEL SELECT PAGE
export const MODEL_SELECT_ENABLE_DRIVING_TYPES =
  "MODEL_SELECT_ENABLE_DRIVING_TYPES";
export const MODEL_SELECT_ENABLE_MISSIONS = "MODEL_SELECT_ENABLE_MISSIONS";
export const MODEL_SELECT_IS_CLOSE_MODAL_OPEN =
  "MODEL_SELECT_IS_CLOSE_MODAL_OPEN";
export const MODEL_SEELCT_IS_SELECT_CAR_MODAL_OPEN =
  "MODEL_SEELCT_IS_SELECT_CAR_MODAL_OPEN";
export const MODEL_SELECT_SELECTED_CATEGORY = "MODEL_SELECT_SELECTED_CATEGORY";
export const MODEL_SELECT_SELECTED_DRIVING_TYPE =
  "MODEL_SELECT_SELECTED_DRIVING_TYPE";
export const MODEL_SELECT_SELECTED_ENGINE = "MODEL_SELECT_SELECTED_ENGINE";
export const MODEL_SELECT_SELECTED_MISSION = "MODEL_SELECT_SELECTED_MISSION";
