// MENU
export const MENU_SELECTED_CATEGORY = "MENU_SELECTED_CATEGORY";
export const MENU_SELECTED_CAR = "MENU_SELECTED_CAR";
export const MENU_IS_OPENED = "MENU_IS_OPENED";

// SELECT MODEL
export const MODEL_SELECTED_CATEGORY = "MODEL_SELECTED_CATEGORY";
export const MODEL_IS_CLOSE_MODAL_OPEN = "IS_CLOSE_MODAL_OPEN";
export const MODEL_IS_SELECT_MODAL_OPEN = "MODEL_IS_SELECT_MODAL_OPEN";
