spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_estimation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

env:
  cors:
    frontend: http://localhost:5173
