spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_estimation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: validate

env:
  cors:
    frontend: http://localhost:5173
---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev
